# Generated by Django 3.1 on 2020-10-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='complement_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='neighborhood_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street_address',
        ),
    ]
