# Generated by Django 3.1 on 2020-09-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200924_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onduty',
            name='day_of_the_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_fired',
            field=models.DateField(blank=True, null=True, verbose_name='Data de desligamento'),
        ),
    ]
