# Generated by Django 3.1 on 2020-09-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200924_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onduty',
            name='day_of_the_week',
            field=models.IntegerField(verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_fired',
            field=models.DateField(verbose_name='Data de desligamento'),
        ),
    ]
