# Generated by Django 3.1 on 2020-10-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bond_type',
            field=models.CharField(blank=True, choices=[('1', 'Coordenador'), ('2', 'Orientador'), ('3', 'Estagiário'), ('4', 'Colaborador Eventual')], max_length=50, null=True, verbose_name='Tipo de vínculo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='scholarship',
            field=models.CharField(blank=True, choices=[('1', 'Bolsista'), ('2', 'Voluntário')], max_length=50, null=True, verbose_name='Bolsista'),
        ),
    ]
