# Generated by Django 3.1 on 2020-09-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200930_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onduty',
            name='day_of_the_week',
            field=models.IntegerField(blank=True, verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
    ]
