# Generated by Django 3.1 on 2020-09-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200930_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_fired',
            field=models.DateField(blank=True, null=True, verbose_name='Data de desligamento'),
        ),
    ]
