# Generated by Django 3.1 on 2020-09-30 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200930_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='on_duty',
        ),
        migrations.AddField(
            model_name='onduty',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='day_of_the_week',
            field=models.IntegerField(verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='end_time',
            field=models.TimeField(verbose_name='Fim plantão'),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='start_time',
            field=models.TimeField(verbose_name='Início plantão'),
        ),
    ]
