# Generated by Django 3.1 on 2020-10-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200930_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_fired',
            field=models.DateField(default=None, verbose_name='Data de desligamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.DeleteModel(
            name='OnDuty',
        ),
    ]
