# Generated by Django 3.1 on 2020-10-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201001_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_fired',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de desligamento'),
        ),
    ]
