# Generated by Django 3.1 on 2020-10-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField(verbose_name='Número do Caso')),
                ('releted_areas', models.CharField(blank=True, choices=[('1', 'Administrativo'), ('2', 'Ambiental'), ('3', 'Cível'), ('4', 'Consumidor'), ('5', 'Criminal')], max_length=3, null=True, verbose_name='Áreas Relacionadas')),
                ('reference_contacts', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Contatos de referência')),
                ('daj_number', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Número do caso no MinhaDAJ')),
                ('daj_advisor', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Orientador no DAJ')),
                ('daj_intern', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Estagiário no DAJ')),
                ('report', models.CharField(blank=True, default=None, max_length=15000, null=True, verbose_name='Relatório')),
                ('registration_date', models.DateField(verbose_name='Data de cadastro')),
                ('solution_date', models.DateField(verbose_name='Data de cadastro')),
            ],
        ),
    ]
