# Generated by Django 3.1 on 2020-09-30 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '__first__'),
        ('axis', '0001_initial'),
        ('tasks', '0002_auto_20200930_0039'),
        ('entities', '0002_entity_name'),
        ('documents', '0002_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lawSuits', '0002_lawsuit_law_suit_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField(verbose_name='Número do Caso')),
                ('releted_areas', models.CharField(blank=True, choices=[('1', 'Administrativo'), ('2', 'Ambiental'), ('3', 'Cível'), ('4', 'Consumidor'), ('5', 'Criminal')], max_length=3, null=True, verbose_name='Áreas Relacionadas')),
                ('reference_contacts', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Contatos de referência')),
                ('daj_number', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Número do caso no MinhaDAJ')),
                ('daj_advisor', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Orientador no DAJ')),
                ('daj_intern', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Estagiário no DAJ')),
                ('report', models.CharField(blank=True, default=None, max_length=15000, null=True, verbose_name='Relatório')),
                ('registration_date', models.DateField(verbose_name='Data de cadastro')),
                ('solution_date', models.DateField(verbose_name='Data de cadastro')),
                ('advisor', models.ManyToManyField(blank=True, related_name='advisor', to=settings.AUTH_USER_MODEL, verbose_name='Oritentador Responsável')),
                ('assisted_person', models.ManyToManyField(blank=True, to='people.Person', verbose_name='Pessoa Assistida')),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='axis.axis', verbose_name='Eixo')),
                ('documents', models.ManyToManyField(blank=True, to='documents.Document', verbose_name='Processos')),
                ('entities', models.ManyToManyField(blank=True, to='entities.Entity', verbose_name='Entidades relacionadas')),
                ('intern', models.ManyToManyField(blank=True, related_name='intern', to=settings.AUTH_USER_MODEL, verbose_name='Estagiário Responsável')),
                ('law_suits', models.ManyToManyField(blank=True, to='lawSuits.LawSuit', verbose_name='Processos')),
                ('tasks', models.ManyToManyField(blank=True, to='tasks.Task', verbose_name='Processos')),
            ],
        ),
    ]
