# Generated by Django 3.1 on 2020-10-01 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('lawSuits', '0001_initial'),
        ('entities', '0001_initial'),
        ('documents', '0001_initial'),
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('axis', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='advisor',
            field=models.ManyToManyField(blank=True, related_name='advisor', to=settings.AUTH_USER_MODEL, verbose_name='Oritentador Responsável'),
        ),
        migrations.AddField(
            model_name='case',
            name='assisted_person',
            field=models.ManyToManyField(blank=True, to='people.Person', verbose_name='Pessoa Assistida'),
        ),
        migrations.AddField(
            model_name='case',
            name='axis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='axis.axis', verbose_name='Eixo'),
        ),
        migrations.AddField(
            model_name='case',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.Document', verbose_name='Processos'),
        ),
        migrations.AddField(
            model_name='case',
            name='entities',
            field=models.ManyToManyField(blank=True, to='entities.Entity', verbose_name='Entidades relacionadas'),
        ),
        migrations.AddField(
            model_name='case',
            name='intern',
            field=models.ManyToManyField(blank=True, related_name='intern', to=settings.AUTH_USER_MODEL, verbose_name='Estagiário Responsável'),
        ),
        migrations.AddField(
            model_name='case',
            name='law_suits',
            field=models.ManyToManyField(blank=True, to='lawSuits.LawSuit', verbose_name='Processos'),
        ),
        migrations.AddField(
            model_name='case',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.Task', verbose_name='Processos'),
        ),
    ]
