# Generated by Django 3.1 on 2020-10-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20201008_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_number',
        ),
    ]
