# Generated by Django 3.1 on 2020-10-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_case_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='solution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de cadastro'),
        ),
    ]
