# Generated by Django 3.1 on 2020-10-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20201010_2335'),
        ('tasks', '0002_auto_20201010_2335'),
        ('cases', '0005_auto_20201015_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.Document', verbose_name='Documentos'),
        ),
        migrations.AlterField(
            model_name='case',
            name='solution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de solução'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.Task', verbose_name='Tarefa'),
        ),
    ]
