# Generated by Django 3.1 on 2020-10-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20201027_0020'),
        ('cases', '0007_auto_20201030_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assisted_person',
            field=models.ManyToManyField(blank=True, related_name='related_case', to='people.Person'),
        ),
    ]
