# Generated by Django 3.1 on 2020-10-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_suits', '0008_auto_20201030_0046'),
        ('people', '0007_auto_20201027_0020'),
        ('documents', '0004_auto_20201031_0303'),
        ('tasks', '0003_task_workflow_state'),
        ('entities', '0002_auto_20201010_2335'),
        ('cases', '0008_auto_20201031_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assisted_person',
            field=models.ManyToManyField(blank=True, related_name='case_people', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='case_documents', to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='case',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='case_entities', to='entities.Entity'),
        ),
        migrations.AlterField(
            model_name='case',
            name='law_suits',
            field=models.ManyToManyField(blank=True, related_name='case_law_suits', to='law_suits.LawSuit'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='case_tasks', to='tasks.Task'),
        ),
    ]
