# Generated by Django 3.1.3 on 2020-12-04 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Ofício'), ('2', 'Parecer'), ('3', 'Nota Técnica'), ('4', 'Amicus Curiae'), ('5', 'Documentos de Assistidos'), ('6', 'Petições'), ('7', 'Atas de Reuniões'), ('8', 'Administrativo'), ('9', 'Outros')], default='1', max_length=1, verbose_name='Tipo de Documento')),
                ('recipients', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Destinatários')),
                ('date', models.DateField(blank=True, help_text='produção/recebimento/envio/protocolo', null=True, verbose_name='Data')),
                ('link', models.URLField(blank=True, default=None, max_length=50, null=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='Rua')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('complement', models.CharField(max_length=200, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(help_text='UF do estado', max_length=2, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='Conteúdo')),
                ('source', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Fonte')),
            ],
            options={
                'verbose_name_plural': 'Frases',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Endereço de e-mail')),
                ('is_staff', models.BooleanField(default=True, verbose_name='É da equipe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada')),
                ('last_login', models.DateField(blank=True, null=True, verbose_name='Último login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('deadline', models.DateField(blank=True, default=None, null=True, verbose_name='Prazo')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('is_done', models.BooleanField(default=False, verbose_name='Feito')),
                ('responsible', models.ManyToManyField(blank=True, related_name='in_charge', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(choices=[('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira')], max_length=1, verbose_name='Dia da semana')),
                ('start_time', models.TimeField(verbose_name='Início do plantão')),
                ('end_time', models.TimeField(verbose_name='Fim do plantão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF')),
                ('cnh', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNH')),
                ('bond_type', models.CharField(blank=True, choices=[('1', 'Coordenador'), ('2', 'Orientador'), ('3', 'Estagiário'), ('4', 'Colaborador Eventual')], max_length=50, null=True, verbose_name='Tipo de vínculo')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('registration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de matrícula')),
                ('course', models.CharField(blank=True, max_length=50, null=True, verbose_name='Curso')),
                ('university', models.CharField(blank=True, max_length=50, null=True, verbose_name='Universidade')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Departamento')),
                ('date_fired', models.DateField(blank=True, default=None, null=True, verbose_name='Data de desligamento')),
                ('scholarship', models.CharField(blank=True, choices=[('1', 'Bolsista'), ('2', 'Voluntário')], max_length=50, null=True, verbose_name='Bolsista')),
                ('scholarship_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de bolsa')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Administracao.endereco')),
                ('axis', models.ManyToManyField(related_name='eixo', to='Administracao.Eixo', verbose_name='Eixo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Nome')),
                ('entity_liked', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Ente Administrativo a que se vincula')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Descrição da atuação')),
                ('contact', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Telefone ou Email Institucional ')),
                ('reference_person', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Nome da pessoa de referência')),
                ('reference_person_contact', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Contato da pessoa de referência')),
                ('comments', models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Observação')),
                ('street', models.CharField(default='', max_length=200, verbose_name='Rua')),
                ('number', models.IntegerField(default='', verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(default='', max_length=50, verbose_name='Bairro')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(default='', max_length=2, verbose_name='UF')),
                ('axis', models.ManyToManyField(related_name='associated_axes', to='Administracao.Eixo', verbose_name='Eixos associados')),
            ],
        ),
    ]
