# Generated by Django 3.1.3 on 2020-12-04 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administracao', '0001_initial'),
        ('Atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='assisted_persons', to='Atendimento.Pessoa', verbose_name='Pessoas assistidas'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administracao.entidade'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.pessoa'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='axis',
            field=models.ManyToManyField(blank=True, related_name='document_axis', to='Administracao.Eixo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='prepared_by',
            field=models.ManyToManyField(blank=True, related_name='developer', to=settings.AUTH_USER_MODEL, verbose_name='Elaborado por'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='document_task', to='Administracao.Tarefa'),
        ),
    ]
