# Generated by Django 3.1.3 on 2020-11-24 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Atendimento', '0001_initial'),
        ('Administracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='assisted_persons', to='Atendimento.Pessoa', verbose_name='Pessoas assistidas'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administracao.entidade'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.pessoa'),
        ),
    ]
