# Generated by Django 3.1.3 on 2020-12-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0002_auto_20201204_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento'),
        ),
    ]
