# Generated by Django 3.1.3 on 2020-11-24 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0002_auto_20201124_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
