# Generated by Django 3.1.3 on 2020-11-25 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0004_auto_20201125_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='axis',
            field=models.ManyToManyField(related_name='document_axis', to='Administracao.Eixo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='date',
            field=models.DateField(blank=True, help_text='produção/recebimento/envio/protocolo', null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='documento',
            name='link',
            field=models.URLField(default=None, max_length=50, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='documento',
            name='prepared_by',
            field=models.ManyToManyField(blank=True, related_name='developer', to=settings.AUTH_USER_MODEL, verbose_name='Elaborado por'),
        ),
        migrations.AddField(
            model_name='documento',
            name='recipients',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Destinatários'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tasks',
            field=models.ManyToManyField(related_name='document_task', to='Administracao.Tarefa'),
        ),
    ]
