# Generated by Django 3.1.3 on 2020-12-05 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0004_remove_perfil_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['perfil'], 'verbose_name_plural': 'Usuários'},
        ),
    ]
