# Generated by Django 3.1.3 on 2020-12-03 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0005_auto_20201125_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='deadline',
            field=models.DateField(default=None, verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='responsible',
            field=models.ManyToManyField(blank=True, related_name='in_charge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
