# Generated by Django 3.1.3 on 2020-12-03 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0006_auto_20201203_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Feito'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='axis',
            field=models.ManyToManyField(blank=True, related_name='document_axis', to='Administracao.Eixo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='link',
            field=models.URLField(blank=True, default=None, max_length=50, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='document_task', to='Administracao.Tarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsible',
            field=models.ManyToManyField(blank=True, related_name='in_charge', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='title',
            field=models.CharField(default='Tarefa sem título', max_length=50, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF')),
                ('cnh', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNH')),
                ('bond_type', models.CharField(blank=True, choices=[('1', 'Coordenador'), ('2', 'Orientador'), ('3', 'Estagiário'), ('4', 'Colaborador Eventual')], max_length=50, null=True, verbose_name='Tipo de vínculo')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('registration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de matrícula')),
                ('course', models.CharField(blank=True, max_length=50, null=True, verbose_name='Curso')),
                ('university', models.CharField(blank=True, max_length=50, null=True, verbose_name='Universidade')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Departamento')),
                ('date_fired', models.DateField(blank=True, default=None, null=True, verbose_name='Data de desligamento')),
                ('scholarship', models.CharField(blank=True, choices=[('1', 'Bolsista'), ('2', 'Voluntário')], max_length=50, null=True, verbose_name='Bolsista')),
                ('scholarship_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de bolsa')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Administracao.endereco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
