# Generated by Django 3.1.3 on 2020-12-06 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0002_auto_20201206_0240'),
        ('Administracao', '0006_auto_20201206_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='reference_function',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='reference_profission',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='reference_sector',
            field=models.CharField(blank=True, help_text='Serviço/Setor a que se vincula', max_length=200, null=True, verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='entidade',
            name='regional_administrativa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Regional administrativa'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='axis',
            field=models.ManyToManyField(blank=True, related_name='document_axis', to='Administracao.Eixo', verbose_name='Eixos relacionados'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='document_task', to='Administracao.Tarefa', verbose_name='Tarefas relacionadas'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Atendimento.pessoa'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='axis',
            field=models.ManyToManyField(blank=True, related_name='associated_axes', to='Administracao.Eixo', verbose_name='Eixos associados'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição da atuação'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='entity_liked',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Ente administrativo a que se vincula'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='reference_person',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='reference_person_contact',
            field=models.CharField(blank=True, default=None, help_text='Telefone/Email', max_length=200, null=True, verbose_name='Contato'),
        ),
    ]
