# Generated by Django 3.1.3 on 2020-12-03 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0007_auto_20201203_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='prepared_by',
            field=models.ManyToManyField(blank=True, related_name='developer', to=settings.AUTH_USER_MODEL, verbose_name='Elaborado por'),
        ),
        migrations.AlterField(
            model_name='plantao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsible',
            field=models.ManyToManyField(blank=True, related_name='in_charge', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
