# Generated by Django 3.1.3 on 2020-12-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0007_auto_20201203_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Conteúdo')),
                ('source', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Fonte')),
            ],
            options={
                'verbose_name_plural': 'Frases',
            },
        ),
    ]
