# Generated by Django 3.1.3 on 2020-12-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0007_auto_20201203_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
