# Generated by Django 3.1.3 on 2020-12-06 23:11

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0007_auto_20201206_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 6), help_text='produção/recebimento/envio/protocolo', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='prepared_by',
            field=models.ManyToManyField(related_name='developer', to=settings.AUTH_USER_MODEL, verbose_name='Elaborado por'),
        ),
    ]
