# Generated by Django 3.1.3 on 2020-12-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0007_auto_20201203_2031'),
        ('Administracao', '0008_auto_20201203_2038'),
    ]

    operations = [
    ]
