# Generated by Django 3.1.3 on 2020-12-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0008_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
