# Generated by Django 3.1.3 on 2020-12-06 23:22

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0008_auto_20201206_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2020, 12, 6, 23, 22, 47, 675441, tzinfo=utc), verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsible',
            field=models.ManyToManyField(related_name='in_charge', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
