# Generated by Django 3.1.3 on 2020-12-04 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0009_auto_20201204_1759'),
        ('Administracao', '0006_endereco_user'),
        ('Administracao', '0008_auto_20201204_1934'),
    ]

    operations = [
    ]
