# Generated by Django 3.1.3 on 2020-12-06 23:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0009_auto_20201206_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2020, 12, 6, 23, 30, 42, 879429, tzinfo=utc), verbose_name='Prazo'),
        ),
    ]
