# Generated by Django 3.1.3 on 2020-12-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0009_merge_20201203_2048'),
        ('Administracao', '0009_auto_20201204_1759'),
    ]

    operations = [
    ]
