# Generated by Django 3.1.3 on 2020-12-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0010_merge_20201204_2023'),
        ('Administracao', '0010_merge_20201204_1852'),
    ]

    operations = [
    ]
