# Generated by Django 3.1.3 on 2020-12-06 23:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0010_auto_20201206_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2020, 12, 6, 23, 56, 0, 108701, tzinfo=utc), verbose_name='Prazo'),
        ),
    ]
