# Generated by Django 3.1.3 on 2020-12-07 00:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0011_auto_20201206_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2020, 12, 7, 0, 19, 20, 583493, tzinfo=utc), verbose_name='Prazo'),
        ),
    ]
