# Generated by Django 3.1.3 on 2020-12-07 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0012_auto_20201206_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['name'], 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='axis',
            field=models.ManyToManyField(related_name='eixo', to='Administracao.Eixo', verbose_name='Eixo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bond_type',
            field=models.CharField(blank=True, choices=[('1', 'Coordenador'), ('2', 'Orientador'), ('3', 'Estagiário'), ('4', 'Colaborador Eventual')], max_length=50, null=True, verbose_name='Tipo de vínculo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cnh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CNH'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='date_fired',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de desligamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='registration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº de matrícula'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='scholarship',
            field=models.CharField(blank=True, choices=[('1', 'Bolsista'), ('2', 'Voluntário')], max_length=50, null=True, verbose_name='Bolsista'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='scholarship_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de bolsa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='university',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Universidade'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 7), help_text='produção/recebimento/envio/protocolo', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='frase',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2020, 12, 7, 22, 41, 59, 652278, tzinfo=utc), verbose_name='Prazo'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
