# Generated by Django 3.1.3 on 2020-12-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0015_auto_20201207_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(default='-', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
