# Generated by Django 3.1 on 2020-10-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('law_suits', '0004_auto_20201008_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudicialAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('1', 'apelação'), ('2', 'agravo de instrumento'), ('3', 'embargos de declaraçã'), ('4', 'agravo interno'), ('5', 'recurso ordinário'), ('6', 'recurso extraordinário'), ('7', 'recurso especial'), ('8', 'habeas corpus'), ('9', 'recurso em sentido estrito'), ('10', 'agravo em execução'), ('11', 'Outro')], max_length=3, null=True, verbose_name='Categoria')),
                ('judicial_appeal_number', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Número do Recurso')),
                ('plenary', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Câmara/Turma/Plenário')),
                ('report', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Relatoria')),
                ('resume', models.CharField(blank=True, default=None, max_length=5000, null=True, verbose_name='Resumo')),
                ('law_suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law_suits.lawsuit')),
            ],
        ),
    ]
