# Generated by Django 3.1 on 2020-10-10 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judicial_appeals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judicialappeal',
            name='resume',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='judicialappeal',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Apelação'), ('2', 'Agravo de instrumento'), ('3', 'Embargos de declaraçã'), ('4', 'Agravo interno'), ('5', 'Recurso ordinário'), ('6', 'Recurso extraordinário'), ('7', 'Recurso especial'), ('8', 'Habeas corpus'), ('9', 'Recurso em sentido estrito'), ('10', 'Agravo em execução'), ('11', 'Outro')], max_length=3, null=True, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='JudicialAppealMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Data')),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Descrição')),
                ('judicial_appeals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial_appeals.judicialappeal')),
            ],
        ),
    ]
