# Generated by Django 3.1 on 2020-10-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judicial_appeals', '0002_auto_20201010_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judicialappealmove',
            old_name='judicial_appeals',
            new_name='judicial_appeal',
        ),
    ]
