# Generated by Django 3.1 on 2020-10-31 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law_suits', '0008_auto_20201030_0046'),
        ('judicial_appeals', '0003_auto_20201029_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judicialappeal',
            name='law_suit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judicial_appeals', to='law_suits.lawsuit'),
        ),
    ]
