# Generated by Django 3.1 on 2020-09-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(default=None, max_length=50, verbose_name='Link'),
        ),
    ]
