# Generated by Django 3.1 on 2020-10-10 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('axis', '0001_initial'),
        ('tasks', '0002_auto_20201010_2335'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='axis',
            field=models.ManyToManyField(related_name='document_axis', to='axis.Axis'),
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data [produção/recebimento/envio/protocolo]'),
        ),
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.CharField(default=None, max_length=50, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='document',
            name='prepared_by',
            field=models.ManyToManyField(blank=True, related_name='prepared_by', to=settings.AUTH_USER_MODEL, verbose_name='Elaborado por'),
        ),
        migrations.AddField(
            model_name='document',
            name='recipients',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Destinatários'),
        ),
        migrations.AddField(
            model_name='document',
            name='tasks',
            field=models.ManyToManyField(related_name='Tarefas', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Ofício'), ('2', 'Parecer'), ('3', 'Nota Técnica'), ('4', 'Amicus Curiae'), ('5', 'Documentos de Assistidos'), ('6', 'Petições'), ('7', 'Atas de Reuniões'), ('8', 'Administrativo'), ('9', 'Outros')], max_length=3, null=True, verbose_name='TIpo de Documento'),
        ),
    ]
