# Generated by Django 3.1 on 2020-10-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_workflow_state'),
        ('documents', '0003_auto_20201030_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tasks',
            field=models.ManyToManyField(related_name='document_task', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Ofício'), ('2', 'Parecer'), ('3', 'Nota Técnica'), ('4', 'Amicus Curiae'), ('5', 'Documentos de Assistidos'), ('6', 'Petições'), ('7', 'Atas de Reuniões'), ('8', 'Administrativo'), ('9', 'Outros')], max_length=3, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
