# Generated by Django 3.1 on 2020-10-10 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ManyToManyField(blank=True, related_name='in_charge', to=settings.AUTH_USER_MODEL),
        ),
    ]
