# Generated by Django 3.1 on 2020-09-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=None, verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Título'),
        ),
    ]
