# Generated by Django 3.1 on 2020-10-24 22:24

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201010_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workflow_state',
            field=django_fsm.FSMField(default='draft', max_length=50),
        ),
    ]
