# Generated by Django 3.1 on 2020-10-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
            ],
        ),
    ]
