# Generated by Django 3.1 on 2020-10-01 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='responsible_advisor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
