# Generated by Django 3.1 on 2020-10-06 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('people', '0003_auto_20201006_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
