# Generated by Django 3.1 on 2020-10-31 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0007_auto_20201027_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='responsible_advisor',
            field=models.ManyToManyField(blank=True, related_name='p_advisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='responsible_intern',
            field=models.ManyToManyField(blank=True, related_name='p_intern', to=settings.AUTH_USER_MODEL),
        ),
    ]
