# Generated by Django 3.1 on 2020-10-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_suits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='action_type',
            field=models.CharField(default=None, max_length=200, verbose_name='Tipo de ação'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='district',
            field=models.CharField(default=None, max_length=200, verbose_name='Comarca'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='followed_by_daj',
            field=models.BooleanField(default=None, verbose_name='Acompanhado pela DAJ'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='has_lawyer',
            field=models.BooleanField(default=None, verbose_name='Possui advogado/defensor constituído nos autos'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='latest_moves',
            field=models.CharField(default=None, max_length=500, verbose_name='Últimas movimentações'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='law_area',
            field=models.CharField(blank=True, choices=[('1', 'Administrativo'), ('2', 'Ambiental'), ('3', 'Cível'), ('4', 'Consumidor'), ('5', 'Criminal'), ('6', 'Família'), ('7', 'Previdenciário'), ('8', 'Sucessões'), ('9', 'Societário'), ('10', 'Trabalhista'), ('11', 'Tributário'), ('12', 'Contratos'), ('13', 'Internacional'), ('14', 'Retificação')], max_length=50, null=True, verbose_name='Área do direito'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='lawyer_contact',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Contato advogado/defenso'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='lawyer_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Nome advogado/defensor'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='minhadaj_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Número MinhaDAJ'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='open_mandate',
            field=models.BooleanField(default=None, verbose_name='Mandado de prisão em aberto'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='start_date',
            field=models.DateField(default=None, verbose_name='Data início [PI/recebimento da denúncia]'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='transit_date',
            field=models.DateField(default=None, verbose_name='Data trânsito em julgado'),
        ),
    ]
