# Generated by Django 3.1 on 2020-10-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law_suits', '0002_auto_20201007_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawsuit',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='district',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='followed_by_daj',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='has_lawyer',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='latest_moves',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='law_area',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='lawyer_contact',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='lawyer_name',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='minhadaj_number',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='open_mandate',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='lawsuit',
            name='transit_date',
        ),
    ]
