# Generated by Django 3.1 on 2020-10-08 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_remove_person_related_law_suit'),
        ('law_suits', '0004_auto_20201008_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_law_suit', to='people.person'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='action_type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Tipo de ação'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Comarca'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='latest_moves',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Últimas movimentações'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data início [PI/recebimento da denúncia]'),
        ),
    ]
