# Generated by Django 3.1 on 2020-10-30 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law_suits', '0005_auto_20201008_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawsuit',
            name='related_person',
        ),
    ]
