# Generated by Django 3.1 on 2020-10-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20201027_0020'),
        ('law_suits', '0006_remove_lawsuit_related_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='related_people',
            field=models.ManyToManyField(null=True, related_name='related_law_suit', to='people.Person'),
        ),
    ]
