# Generated by Django 3.1 on 2020-10-10 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('people', '0006_remove_person_related_law_suit'),
        ('axis', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
        migrations.AddField(
            model_name='entity',
            name='axis',
            field=models.ManyToManyField(blank=True, related_name='Eixo', to='axis.Axis'),
        ),
        migrations.AddField(
            model_name='entity',
            name='comments',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='entity',
            name='contact',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Telefone ou Email Institucional '),
        ),
        migrations.AddField(
            model_name='entity',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Descrição da atuação'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_liked',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Ente Administrativo a que se vincula'),
        ),
        migrations.AddField(
            model_name='entity',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='assisted_persons', to='people.Person'),
        ),
        migrations.AddField(
            model_name='entity',
            name='reference_person',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Pessoa de referência'),
        ),
        migrations.AddField(
            model_name='entity',
            name='reference_person_contact',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Contato da pessoa de referência'),
        ),
    ]
