# Generated by Django 3.1 on 2020-10-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis', '0001_initial'),
        ('entities', '0002_auto_20201010_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='axis',
            field=models.ManyToManyField(blank=True, related_name='associated_axes', to='axis.Axis'),
        ),
    ]
