# Generated by Django 3.1.3 on 2020-11-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caso',
            options={'verbose_name_plural': 'Casos'},
        ),
        migrations.AlterModelOptions(
            name='historicorecurso',
            options={'verbose_name_plural': 'Movimentações no recurso'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='processo',
            options={'verbose_name_plural': 'Processos'},
        ),
        migrations.AlterModelOptions(
            name='recurso',
            options={'verbose_name_plural': 'Recursos'},
        ),
    ]
