# Generated by Django 3.1.3 on 2020-12-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0002_auto_20201206_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='related_areas',
            field=models.CharField(choices=[('1', 'Administrativo'), ('2', 'Ambiental'), ('3', 'Cível'), ('4', 'Consumidor'), ('5', 'Criminal'), ('6', 'Família'), ('7', 'Ambiental'), ('8', 'Previdenciário'), ('9', 'Sucessões'), ('10', 'Societário'), ('11', 'Trabalhista'), ('12', 'Tributário'), ('13', 'Contratos'), ('14', 'Internacional')], default=1, max_length=3, verbose_name='Áreas relacionadas'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='report',
            field=models.TextField(default='', max_length=15000, verbose_name='Relatório'),
        ),
    ]
