# Generated by Django 3.1.3 on 2020-12-06 23:56

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Atendimento', '0003_auto_20201206_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='complement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='assisted',
            field=models.BooleanField(default=False, verbose_name='Pessoa assistida?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='birth_city',
            field=models.CharField(default='', max_length=50, verbose_name='Cidade de nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='birth_state',
            field=models.CharField(default='', max_length=50, verbose_name='Estado de nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='civil_status',
            field=models.CharField(choices=[('1', 'Solteira'), ('2', 'Casada'), ('3', 'Separada'), ('4', 'Divorciada'), ('5', 'Viúva')], default=1, max_length=3, verbose_name='Estado civíl'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='first_appointment_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 6, 23, 56, 0, 122935, tzinfo=utc), verbose_name='Data do primeiro atendimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='responsible_advisor',
            field=models.ManyToManyField(related_name='p_advisor', to=settings.AUTH_USER_MODEL, verbose_name='Orientadora responsável'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='responsible_intern',
            field=models.ManyToManyField(related_name='p_intern', to=settings.AUTH_USER_MODEL, verbose_name='Estagiária responsável'),
        ),
    ]
