# Generated by Django 3.1.3 on 2020-12-07 00:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0004_auto_20201206_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='transit_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data trânsito em julgado'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='first_appointment_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 7, 0, 19, 20, 595900, tzinfo=utc), verbose_name='Data do primeiro atendimento'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='action_type',
            field=models.CharField(default='', max_length=200, verbose_name='Tipo de ação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='district',
            field=models.CharField(default='', max_length=200, verbose_name='Comarca'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='followed_by_daj',
            field=models.BooleanField(default=False, verbose_name='Acompanhado pela DAJ'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='has_lawyer',
            field=models.BooleanField(default=False, verbose_name='Possui advogado/defensor constituído nos autos?'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='law_area',
            field=models.CharField(choices=[('1', 'Administrativo'), ('2', 'Ambiental'), ('3', 'Cível'), ('4', 'Consumidor'), ('5', 'Criminal'), ('6', 'Família'), ('7', 'Previdenciário'), ('8', 'Sucessões'), ('9', 'Societário'), ('10', 'Trabalhista'), ('11', 'Tributário'), ('12', 'Contratos'), ('13', 'Internacional'), ('14', 'Retificação')], default=1, max_length=3, verbose_name='Área do direito'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='start_date',
            field=models.DateField(default=None, verbose_name='Data início [PI/recebimento da denúncia]'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='transit_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data trânsito em julgado'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='law_suit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judicial_appeals', to='Atendimento.processo', verbose_name='Processo'),
        ),
    ]
