# Generated by Django 3.1.3 on 2020-12-07 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0005_auto_20201206_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='first_appointment_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 7, 22, 41, 59, 668242, tzinfo=utc), verbose_name='Data do primeiro atendimento'),
        ),
    ]
