# Generated by Django 3.1.3 on 2020-12-07 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0008_auto_20201207_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='first_appointment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do primeiro atendimento'),
        ),
    ]
