# Generated by Django 3.1.3 on 2021-02-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atendimento', '0011_observacoespessoa_observacoesprocesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Caso Ativo?'),
        ),
        migrations.AddField(
            model_name='caso',
            name='is_amicus_curiae',
            field=models.BooleanField(default=False, verbose_name='Amicus Curiae?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='civil_status',
            field=models.CharField(choices=[('1', 'Solteira'), ('2', 'Casada'), ('3', 'Separada'), ('4', 'Divorciada'), ('5', 'Viúva'), ('6', 'União estável')], default=1, max_length=3, verbose_name='Estado civíl'),
        ),
    ]
