# Generated by Django 3.1 on 2020-10-07 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_knew_about_drs', models.CharField(blank=True, max_length=100, null=True)),
                ('current_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('had_other_occupations', models.CharField(blank=True, max_length=100, null=True)),
                ('relevant_information', models.CharField(blank=True, max_length=100, null=True)),
                ('last_attendance_date', models.DateField()),
                ('how_knew_about_transpasse', models.CharField(blank=True, max_length=100, null=True)),
                ('lives_with', models.CharField(blank=True, max_length=100, null=True)),
                ('cities_lived', models.CharField(blank=True, max_length=100, null=True)),
                ('ist_exams_up_to_date', models.BooleanField(default=False)),
                ('last_time_been_health_center', models.CharField(blank=True, max_length=100, null=True)),
                ('is_drug_user', models.BooleanField(blank=True, default=False, null=True)),
                ('which_drugs', models.CharField(blank=True, max_length=100, null=True)),
                ('consider_drugs_bad', models.BooleanField(blank=True, default=False, null=True)),
                ('uses_hormones', models.BooleanField(blank=True, default=False, null=True)),
                ('use_accompanied_by_doctor', models.BooleanField(blank=True, default=False, null=True)),
                ('which_hormones', models.CharField(blank=True, max_length=100, null=True)),
                ('works', models.BooleanField(blank=True, default=False, null=True)),
                ('where_works', models.CharField(blank=True, max_length=100, null=True)),
                ('already_worked', models.BooleanField(blank=True, default=False, null=True)),
                ('where_worked', models.CharField(blank=True, max_length=100, null=True)),
                ('interests', models.CharField(blank=True, max_length=100, null=True)),
                ('makes_track', models.BooleanField(blank=True, default=False, null=True)),
                ('track_type', models.CharField(blank=True, max_length=100, null=True)),
                ('where_makes_track', models.CharField(blank=True, max_length=100, null=True)),
                ('documents_owned', models.CharField(blank=True, max_length=100, null=True)),
                ('rectified_name_and_gender', models.BooleanField(blank=True, default=False, null=True)),
                ('willing_to_rectify', models.BooleanField(blank=True, default=False, null=True)),
                ('been_arrested', models.BooleanField(blank=True, default=False, null=True)),
                ('city_arrested', models.CharField(blank=True, max_length=100, null=True)),
                ('year_arrested', models.CharField(blank=True, max_length=20, null=True)),
                ('was_processed', models.BooleanField(blank=True, default=False, null=True)),
                ('entities', models.ManyToManyField(related_name='entity', to='entities.Entity')),
                ('psychology_intern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Estagiária de psicologia')),
            ],
        ),
    ]
