# Generated by Django 3.1 on 2020-10-31 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20201031_1943'),
        ('attendance', '0002_attendance_assisted_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='assisted_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='people.person'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last_attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
