# Generated by Django 3.1 on 2020-11-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis', '0001_initial'),
        ('attendance', '0004_remove_attendance_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='axis',
            field=models.ManyToManyField(related_name='attendance_axis', to='axis.Axis'),
        ),
    ]
